# Generated by Django 3.2.9 on 2022-04-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
