# Generated by Django 3.2.9 on 2022-04-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_new_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Listing',
        ),
    ]
