# Generated by Django 3.2.9 on 2022-04-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
    ]
