# Generated by Django 3.2.9 on 2022-04-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='No description', max_length=256),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='title', max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.CharField(default='picture', max_length=128),
        ),
    ]
