# Generated by Django 3.2.9 on 2022-04-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220423_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOME', 'Home & Garden'), ('CLOTHING', 'Clothing and Apparel')], default='Home', max_length=32),
        ),
    ]
