# Generated by Django 3.2.9 on 2022-04-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing & Apparel'), ('ELECTRONICS', 'Electronics'), ('HOME', 'Home & Garden'), ('TOYS', 'Toys')], default='Home', max_length=32),
        ),
    ]
