# Generated by Django 4.0.1 on 2022-05-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_watchlist_item_watchlist_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='auctions.listing'),
        ),
    ]
