# Generated by Django 4.0.4 on 2022-05-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_price_listing_bid_alter_watchlist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
