# Generated by Django 4.0.4 on 2022-05-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='bid',
        ),
    ]
