# Generated by Django 4.0.4 on 2022-05-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_rename_price_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
