# Generated by Django 4.0.4 on 2022-05-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listing'),
        ),
    ]
