# Generated by Django 4.0.4 on 2022-05-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_auction_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.listing'),
        ),
    ]
