# Generated by Django 4.0.4 on 2022-05-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_remove_auction_id_alter_auction_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='title',
            new_name='listing',
        ),
    ]
