# Generated by Django 4.0.6 on 2022-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_remove_auction_bid_alter_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
