# Generated by Django 4.0.6 on 2022-08-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_alter_listing_picture_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
