# Generated by Django 4.0.6 on 2022-08-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_bid_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
    ]
