# Generated by Django 4.0.6 on 2022-08-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_rename_bid_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='auction',
        ),
    ]
