# Generated by Django 4.0.6 on 2022-09-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_alter_bid_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='winner',
            new_name='bidder',
        ),
    ]
