# Generated by Django 4.0.4 on 2022-09-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
