# Generated by Django 4.0.4 on 2022-09-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0054_remove_comments_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='time',
            new_name='timestamp',
        ),
    ]
