# Generated by Django 4.0.4 on 2022-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0055_rename_time_bid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
